name: Python package

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
        - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s--health-timeout=5s --health-retries=3
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
          
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Verify MySQL connection from host
        run: |
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port 32574 -uroot -ppassword -e "SHOW DATABASES"
           
      - name: Test with pytest
        run: |
          pytest
